import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SidebarProvider } from "@/components/ui/sidebar";
import QueryProvider from "@/providers/queryProvider";
import { AuthProvider } from "@/providers/authProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Hospital Ward Monitoring App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} w-full antialiased`}
      >
        <QueryProvider>
          <SidebarProvider>
            <AuthProvider>
              <main className="w-full">{children}</main>
            </AuthProvider>
          </SidebarProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
