'use client';

import './globals.css';
import { Inter } from 'next/font/google';

import Header from '@/components/Header';
import { QueryClientProvider, QueryClient } from 'react-query';

const inter = Inter({ subsets: ['latin'] });

const queryClient = new QueryClient({
  defaultOptions: {
    queries: {
      cacheTime: 1000 * 60 * 60
    }
  }
});

// export const metadata = {
//   title: 'Room Monitor',
//   description: 'Generated by create next app'
// };

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <head>
        <title>Room Monitor</title>
      </head>
      <body className={inter.className}>
        <Header />
        <main className='md:h-[80vh]'>
          <QueryClientProvider client={queryClient}>
            {children}
          </QueryClientProvider>
        </main>
      </body>
    </html>
  );
}
