import type { Metadata } from "next";
import { AppSidebar } from "@/components/appSidebar";

export const metadata: Metadata = {
  title: "Hospital Ward Monitoring App",
  description: "Generated by create next app",
};

export default function MainAppLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
      <div className="w-full flex">
        <AppSidebar />
        <div className="w-full">{children}</div>
      </div>
    </div>
  );
}
